In [1]:
import pandas as pd
import numpy as np

In [3]:
#reading file

df= pd.read_csv('/Users/morgan/Desktop/SEIS 763 ML/FINAL PROJECT/Final Project Data Files/ML_job_postings_finale_ready_v2.csv',header=0)
df.head()

,job_id,title,work_type,description,location,zip_code,min_salary,max_salary,normalized_salary,views,...,sector,city,state,name,latitude,longitude,gdp,income,region,moving_score
0,1014822088,Marketing Specialist,FULL_TIME,About TrackerTracker is a leading global cloud...,United States,NaN,70000.0,80000.0,75000.0,7.0,...,Information Technology,United States,US,Remote,NaN,NaN,483162.0,416325.0,Plains,50.000000
1,3189117072,Client Service Associate / Practice Manager,FULL_TIME,Company OverviewSignature Estate and Investmen...,"Redondo Beach, CA",90277.0,70000.0,100000.0,85000.0,6.0,...,Energy,Redondo Beach,CA,California,36.778261,-119.417932,3870379.0,3166135.0,Far West,4.214518
2,3260455681,Operations Specialist,FULL_TIME,Weyerhaeuser is searching for a Operations Spe...,"Castle Rock, WA",98611.0,72742.0,109113.0,90927.5,18.0,...,Materials,Castle Rock,WA,Washington,47.751074,-120.740139,807865.0,632296.0,Far West,4.703287
3,3277232283,HR & Administrative Assistant,FULL_TIME,HR & Administrative CoordinatorWork is Remote ...,United States,NaN,55000.0,72000.0,63500.0,59.0,...,Energy,United States,US,Remote,NaN,NaN,483162.0,416325.0,Plains,50.000000
4,3297645846,Contract Administrator,FULL_TIME,Contract AdministratorSummary of PositionThe C...,"Broomfield, CO",80020.0,74400.0,90000.0,82200.0,6.0,...,Materials,Broomfield,CO,Colorado,39.550051,-105.782067,529627.0,470606.0,Rocky Mountain,8.368978

In [5]:
df.shape

(3902, 50)

In [9]:
df.dtypes

job_id                           int64
title                           object
work_type                       object
description                     object
location                        object
zip_code                       float64
min_salary                     float64
max_salary                     float64
normalized_salary              float64
views                          float64
original_listed_time            object
expiry                          object
day_posting                      int64
is_data_related                   bool
formatted_experience_level      object
degree_level                    object
job_classification              object
soft_skills                     object
programming_languages_score      int64
analysis_statistics_score        int64
machine_learning_score           int64
data_visualization_score         int64
cloud_platform_score             int64
database_score                   int64
big_data_tools_score             int64
big_data_score                   int64
business_engineering_score       int64
company_id                     float64
company_name                    object
company desc                    object
company_size                   float64
country                         object
headquarter state               object
headquarter city                object
headquarter addr                object
headquarter zipcode             object
industry                        object
speciality                      object
employee_count                   int64
follower_count                   int64
sector                          object
city                            object
state                           object
name                            object
latitude                       float64
longitude                      float64
gdp                            float64
income                         float64
region                          object
moving_score                   float64
dtype: object

In [11]:
df.columns

Index(['job_id', 'title', 'work_type', 'description', 'location', 'zip_code',
       'min_salary', 'max_salary', 'normalized_salary', 'views',
       'original_listed_time', 'expiry', 'day_posting', 'is_data_related',
       'formatted_experience_level', 'degree_level', 'job_classification',
       'soft_skills', 'programming_languages_score',
       'analysis_statistics_score', 'machine_learning_score',
       'data_visualization_score', 'cloud_platform_score', 'database_score',
       'big_data_tools_score', 'big_data_score', 'business_engineering_score',
       'company_id', 'company_name', 'company desc', 'company_size', 'country',
       'headquarter state', 'headquarter city', 'headquarter addr',
       'headquarter zipcode', 'industry', 'speciality', 'employee_count',
       'follower_count', 'sector', 'city', 'state', 'name', 'latitude',
       'longitude', 'gdp', 'income', 'region', 'moving_score'],
      dtype='object')

In [17]:
Stats= df.describe()

In [35]:
Stats= Stats.T

In [23]:
df.count()

job_id                         3902
title                          3902
work_type                      3902
description                    3902
location                       3902
zip_code                       3025
min_salary                     3674
max_salary                     3674
normalized_salary              3902
views                          3857
original_listed_time           3902
expiry                         3902
day_posting                    3902
is_data_related                3902
formatted_experience_level     2929
degree_level                   3902
job_classification             3902
soft_skills                    3564
programming_languages_score    3902
analysis_statistics_score      3902
machine_learning_score         3902
data_visualization_score       3902
cloud_platform_score           3902
database_score                 3902
big_data_tools_score           3902
big_data_score                 3902
business_engineering_score     3902
company_id                     3902
company_name                   3902
company desc                   3886
company_size                   3803
country                        3902
headquarter state              3902
headquarter city               3902
headquarter addr               3901
headquarter zipcode            3902
industry                       3902
speciality                     3212
employee_count                 3902
follower_count                 3902
sector                         3902
city                           3902
state                          3902
name                           3902
latitude                       3117
longitude                      3117
gdp                            3902
income                         3902
region                         3902
moving_score                   3902
dtype: int64

In [31]:
df.isnull().sum()

job_id                           0
title                            0
work_type                        0
description                      0
location                         0
zip_code                       877
min_salary                     228
max_salary                     228
normalized_salary                0
views                           45
original_listed_time             0
expiry                           0
day_posting                      0
is_data_related                  0
formatted_experience_level     973
degree_level                     0
job_classification               0
soft_skills                    338
programming_languages_score      0
analysis_statistics_score        0
machine_learning_score           0
data_visualization_score         0
cloud_platform_score             0
database_score                   0
big_data_tools_score             0
big_data_score                   0
business_engineering_score       0
company_id                       0
company_name                     0
company desc                    16
company_size                    99
country                          0
headquarter state                0
headquarter city                 0
headquarter addr                 1
headquarter zipcode              0
industry                         0
speciality                     690
employee_count                   0
follower_count                   0
sector                           0
city                             0
state                            0
name                             0
latitude                       785
longitude                      785
gdp                              0
income                           0
region                           0
moving_score                     0
dtype: int64

In [37]:
#save to csv
Stats.to_csv('df_describe.csv', index=False)

In [49]:
Stats.count()

count    25
mean     25
std      25
min      25
25%      25
50%      25
75%      25
max      25
dtype: int64